# Generated by Django 4.2.30 on 2026-09-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='layout_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_layouts/'),
        ),
        migrations.AddField(
            model_name='zone',
            name='process_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
