# Generated by Django 4.2.30 on 2026-09-17 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_site_layout_image_zone_process_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pid_documents/')),
                ('page_count', models.IntegerField(default=1)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('processing_status', models.CharField(default='UPLOADED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_documents', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='PIDLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField()),
                ('line_style', models.CharField(blank=True, max_length=50, null=True)),
                ('line_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('semantic_type', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('line_number', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(default='UNKNOWN', max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PIDObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
                ('subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('bbox', models.JSONField()),
                ('center_x', models.FloatField(blank=True, null=True)),
                ('center_y', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('source', models.CharField(default='yolo', max_length=100)),
                ('raw_label', models.CharField(blank=True, max_length=255, null=True)),
                ('normalized_label', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PIDPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=1)),
                ('image_reference', models.FileField(blank=True, null=True, upload_to='pid_pages/')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('scale_metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pid_engine.piddocument')),
            ],
        ),
        migrations.CreateModel(
            name='PIDText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('bbox', models.JSONField()),
                ('text_type', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('normalized_text', models.TextField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='pid_engine.pidpage')),
            ],
        ),
        migrations.CreateModel(
            name='PIDZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='candidate', max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('geometry', models.JSONField(blank=True, default=dict)),
                ('evidence_summary', models.JSONField(blank=True, default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='pid_engine.piddocument')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_patterns', models.JSONField(blank=True, default=list)),
                ('stream_patterns', models.JSONField(blank=True, default=list)),
                ('utility_patterns', models.JSONField(blank=True, default=list)),
                ('tag_patterns', models.JSONField(blank=True, default=list)),
                ('label_patterns', models.JSONField(blank=True, default=list)),
                ('required_patterns', models.JSONField(blank=True, default=list)),
                ('optional_patterns', models.JSONField(blank=True, default=list)),
                ('forbidden_patterns', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(max_length=100)),
                ('process_subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(default='inference', max_length=50)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='pid_engine.pidzone')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLegend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('symbol_rules', models.JSONField(blank=True, default=list)),
                ('line_rules', models.JSONField(blank=True, default=list)),
                ('tag_rules', models.JSONField(blank=True, default=list)),
                ('equipment_rules', models.JSONField(blank=True, default=list)),
                ('process_rules', models.JSONField(blank=True, default=list)),
                ('custom_abbreviations', models.JSONField(blank=True, default=dict)),
                ('custom_service_codes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legends', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(max_length=100)),
                ('rule_triggered', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('explanation', models.TextField()),
                ('source_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_engine.pidline')),
                ('source_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_engine.pidobject')),
                ('source_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_engine.pidtext')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='pid_engine.pidzone')),
            ],
        ),
        migrations.AddField(
            model_name='pidobject',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='pid_engine.pidpage'),
        ),
        migrations.AddField(
            model_name='pidline',
            name='end_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines_ending_here', to='pid_engine.pidobject'),
        ),
        migrations.AddField(
            model_name='pidline',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pid_engine.pidpage'),
        ),
        migrations.AddField(
            model_name='pidline',
            name='start_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines_starting_here', to='pid_engine.pidobject'),
        ),
        migrations.CreateModel(
            name='PIDGraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pid_engine.piddocument')),
                ('object_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_engine.pidobject')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pid_engine.pidpage')),
            ],
        ),
        migrations.CreateModel(
            name='PIDGraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(max_length=50)),
                ('direction', models.CharField(default='FORWARD', max_length=50)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='pid_engine.piddocument')),
                ('line_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_engine.pidline')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='pid_engine.pidgraphnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='pid_engine.pidgraphnode')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorityCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_or_zone', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='pid_engine.piddocument')),
            ],
        ),
    ]
