# Generated by Django 4.2.30 on 2026-09-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0002_watersink_is_terminal_watersink_recovery_source'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PAUSED', 'Paused'), ('RUNNING', 'Running')], default='PAUSED', max_length=20)),
                ('current_timestamp', models.DateTimeField(blank=True, null=True)),
                ('speed_multiplier', models.IntegerField(default=1)),
                ('step_interval_seconds', models.IntegerField(default=300)),
                ('current_scenario', models.CharField(default='NORMAL', max_length=50)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_state', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('flow_rate', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('tds', models.FloatField(blank=True, null=True)),
                ('turbidity', models.FloatField(blank=True, null=True)),
                ('tss', models.FloatField(blank=True, null=True)),
                ('bod', models.FloatField(blank=True, null=True)),
                ('cod', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('scenario', models.CharField(default='NORMAL', max_length=50)),
                ('sink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.watersink')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sites.site')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.watersource')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.zone')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['site', 'timestamp'], name='simulation__site_id_420294_idx'), models.Index(fields=['source', 'timestamp'], name='simulation__source__762b81_idx'), models.Index(fields=['sink', 'timestamp'], name='simulation__sink_id_5ede6c_idx')],
            },
        ),
    ]
