# Generated by Django 4.2.30 on 2026-09-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('optimal', 'Optimal'), ('infeasible', 'Infeasible'), ('error', 'Error')], default='pending', max_length=20)),
                ('objective_value', models.FloatField(blank=True, null=True)),
                ('freshwater_consumption', models.FloatField(blank=True, null=True)),
                ('reuse_flow', models.FloatField(blank=True, null=True)),
                ('treatment_flow', models.FloatField(blank=True, null=True)),
                ('estimated_operating_cost', models.FloatField(blank=True, null=True)),
                ('unmet_demand_json', models.JSONField(blank=True, default=dict)),
                ('solver_name', models.CharField(default='PuLP/CBC', max_length=100)),
                ('solver_status', models.CharField(blank=True, default='', max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to='sites.site')),
            ],
            options={
                'db_table': 'optimization_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_flow', models.FloatField()),
                ('quality_status', models.CharField(default='compatible', max_length=50)),
                ('treatment_required', models.BooleanField(default=False)),
                ('routing_cost', models.FloatField(default=0.0)),
                ('treatment_cost', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('optimization_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='optimization.optimizationrun')),
                ('sink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.watersink')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.watersource')),
                ('treatment_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.treatmentoption')),
            ],
            options={
                'db_table': 'optimization_routes',
            },
        ),
    ]
