# Generated by Django 4.2.30 on 2026-09-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('water_quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('available_flow', models.FloatField(help_text='Available flow capacity')),
                ('unit', models.CharField(default='m3/h', max_length=20)),
                ('location', models.JSONField(blank=True, null=True)),
                ('is_freshwater', models.BooleanField(default=False)),
                ('quality_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='water_quality.waterqualityprofile')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='sites.site')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.zone')),
            ],
        ),
        migrations.CreateModel(
            name='WaterSink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sink_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_flow', models.FloatField(help_text='Required flow demand')),
                ('unit', models.CharField(default='m3/h', max_length=20)),
                ('location', models.JSONField(blank=True, null=True)),
                ('allow_partial_demand', models.BooleanField(default=True)),
                ('quality_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='water_quality.waterqualityrequirement')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinks', to='sites.site')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.zone')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('treatment_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_flow', models.FloatField(blank=True, null=True)),
                ('cost_per_unit', models.FloatField(default=0.0, help_text='Cost per m3 treated')),
                ('fixed_cost', models.FloatField(default=0.0)),
                ('output_quality_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='water_quality.waterqualityprofile')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_cost', models.FloatField(default=0.0)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='network.watersink')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='sites.site')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='network.watersource')),
                ('treatment_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.treatmentoption')),
            ],
            options={
                'unique_together': {('source', 'sink', 'treatment_option')},
            },
        ),
    ]
