# Generated by Django 4.2.30 on 2026-09-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersink',
            name='is_terminal',
            field=models.BooleanField(default=False, help_text='True if water leaves the system completely at this node'),
        ),
        migrations.AddField(
            model_name='watersink',
            name='recovery_source',
            field=models.OneToOneField(blank=True, help_text="The source generated by this sink's discharge", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_from_sink', to='network.watersource'),
        ),
    ]
