import React, { useState, useEffect } from 'react';
import { getAIRecommendations, updateAIRecommendation } from '../services/api';
import { useSite } from '../hooks/useSite';

function PriorityBadge({ v }) {
    const m = { low: 'badge-green', medium: 'badge-blue', high: 'badge-amber', urgent: 'badge-red' };
    return <span className={`badge ${m[v] || 'badge-muted'}`}>{v}</span>;
}
function StatusBadge({ v }) {
    const m = { pending: 'badge-amber', flagged: 'badge-red', acknowledged: 'badge-blue', implemented: 'badge-green', dismissed: 'badge-muted' };
    return <span className={`badge ${m[v] || 'badge-muted'}`}>{v?.replace('_', ' ')}</span>;
}

export default function AIAdvisoryPage() {
    const { activeSiteId } = useSite();
    const [recs, setRecs] = useState([]);
    const [loading, setLoading] = useState(true);
    const [message, setMessage] = useState('');

    const load = () => {
        if (!activeSiteId) return;
        setLoading(true);
        getAIRecommendations(activeSiteId).then(setRecs).catch(() => { }).finally(() => setLoading(false));
    };

    useEffect(() => { load(); }, [activeSiteId]);

    const handleStatusUpdate = async (rec, status) => {
        try {
            await updateAIRecommendation(rec.id, { status });
            setMessage(`Recommendation #${rec.id} status updated to "${status}"`);
            load();
        } catch { }
    };

    return (
        <>
            <div className="page-header">
                <div className="flex items-center justify-between" style={{ paddingBottom: 20 }}>
                    <div>
                        <h1 className="page-title">AI Advisory</h1>
                        <p className="page-subtitle" style={{ paddingBottom: 0 }}>
                            Rule-based + LLM contamination advisory recommendations for authority review
                        </p>
                    </div>
                    <button className="btn btn-secondary btn-sm" onClick={load}>↻ Refresh</button>
                </div>
            </div>

            <div className="page-body">
                <div className="alert alert-info mb-4">
                    🤖 These recommendations are <strong>advisory only</strong>. No action is automatically taken.
                    Only mark as "Implemented" after an authorized person has confirmed the action.
                </div>

                {message && <div className="alert alert-success mb-4">{message}</div>}

                {loading ? (
                    <div className="loading-state"><div className="spinner" /><span>Loading recommendations…</span></div>
                ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                        {recs.length === 0 && (
                            <div className="card"><div className="card-body" style={{ textAlign: 'center', color: 'var(--color-text-muted)' }}>
                                No AI recommendations yet. Submit a contamination report and use "AI Analyze".
                            </div></div>
                        )}
                        {recs.map((r) => (
                            <div key={r.id} className="card">
                                <div className="card-body">
                                    <div className="flex items-center justify-between mb-4">
                                        <div className="flex items-center gap-3">
                                            <PriorityBadge v={r.priority} />
                                            <StatusBadge v={r.status} />
                                            <span className="text-muted" style={{ fontSize: '0.78rem' }}>
                                                Generated by: <strong style={{ color: 'var(--color-text-secondary)' }}>{r.generated_by}</strong>
                                                &nbsp;·&nbsp;{new Date(r.created_at).toLocaleString()}
                                            </span>
                                            {r.report_title && (
                                                <span className="text-muted" style={{ fontSize: '0.78rem' }}>
                                                    Re: <em>{r.report_title}</em>
                                                </span>
                                            )}
                                        </div>
                                        <select
                                            className="form-select"
                                            style={{ width: 'auto', padding: '6px 12px', fontSize: '0.8rem' }}
                                            value={r.status}
                                            onChange={(e) => handleStatusUpdate(r, e.target.value)}
                                        >
                                            <option value="pending">Pending</option>
                                            <option value="flagged">Flagged</option>
                                            <option value="acknowledged">Acknowledged</option>
                                            <option value="implemented">Implemented</option>
                                            <option value="dismissed">Dismissed</option>
                                        </select>
                                    </div>

                                    <div style={{ marginBottom: 12 }}>
                                        <div className="form-label">Recommendation</div>
                                        <p style={{ color: 'var(--color-text-primary)', fontSize: '0.9rem' }}>{r.recommendation}</p>
                                    </div>

                                    <div style={{ marginBottom: 12 }}>
                                        <div className="form-label">Reasoning</div>
                                        <p style={{ color: 'var(--color-text-secondary)', fontSize: '0.85rem' }}>{r.reasoning_summary}</p>
                                    </div>

                                    <div style={{
                                        background: 'rgba(0,212,255,0.05)',
                                        border: '1px solid rgba(0,212,255,0.15)',
                                        borderRadius: 'var(--radius-md)',
                                        padding: '12px 16px'
                                    }}>
                                        <div className="form-label">Recommended Action (AUTHORITY REVIEW REQUIRED)</div>
                                        <p style={{ color: 'var(--color-text-primary)', fontSize: '0.875rem', whiteSpace: 'pre-wrap' }}>
                                            {r.recommended_action}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </>
    );
}
