# Generated by Django 4.2.30 on 2026-09-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(help_text='Source dataset or measurement reference', max_length=255)),
                ('measurement_time', models.DateTimeField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('tss', models.FloatField(blank=True, help_text='Total Suspended Solids (mg/L)', null=True)),
                ('cod', models.FloatField(blank=True, help_text='Chemical Oxygen Demand (mg/L)', null=True)),
                ('bod', models.FloatField(blank=True, help_text='Biological Oxygen Demand (mg/L)', null=True)),
                ('tds', models.FloatField(blank=True, help_text='Total Dissolved Solids (mg/L)', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature (°C)', null=True)),
                ('conductivity', models.FloatField(blank=True, help_text='Conductivity (µS/cm)', null=True)),
                ('other_parameters', models.JSONField(blank=True, default=dict, help_text='Additional site-specific parameters as key-value pairs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'water_quality_profiles',
            },
        ),
        migrations.CreateModel(
            name='WaterQualityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ph_min', models.FloatField(blank=True, null=True)),
                ('ph_max', models.FloatField(blank=True, null=True)),
                ('tss_max', models.FloatField(blank=True, null=True)),
                ('cod_max', models.FloatField(blank=True, null=True)),
                ('bod_max', models.FloatField(blank=True, null=True)),
                ('tds_max', models.FloatField(blank=True, null=True)),
                ('temperature_min', models.FloatField(blank=True, null=True)),
                ('temperature_max', models.FloatField(blank=True, null=True)),
                ('other_limits', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'water_quality_requirements',
            },
        ),
        migrations.CreateModel(
            name='TNPCBReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_reference', models.CharField(help_text='Original TNPCB station/source identifier', max_length=512)),
                ('location', models.JSONField(blank=True, null=True)),
                ('sample_time', models.DateTimeField(blank=True, null=True)),
                ('parameter_name', models.CharField(max_length=255)),
                ('parameter_value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('dataset_name', models.CharField(max_length=255)),
                ('dataset_reference', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tnpcb_readings', to='sites.site')),
            ],
            options={
                'db_table': 'tnpcb_readings',
            },
        ),
    ]
